# Generated by Django 5.0.1 on 2024-02-04 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('syallabus', models.TextField()),
                ('eligibility', models.TextField()),
                ('official_website', models.URLField()),
                ('courses_offered', models.TextField()),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examindex')),
            ],
        ),
    ]
