# Generated by Django 5.0.1 on 2024-02-06 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamDetails',
            new_name='ExamDetail',
        ),
    ]
