# Generated by Django 5.0.1 on 2024-02-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_rename_examdetails_examdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='examindex',
            name='stream',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
